src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Carbon\Carbon;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $contenu;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $featured_image;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * un article est possédé par un utilisateur.
     *
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * un article appartient à une catégorie.
     *
     * @ORM\ManyToMany(targetEntity=Categorie::class, inversedBy="categories")
     */
    private $categories;

    /**
     * un article appartient à un mot-clé.
     *
     * @ORM\ManyToMany(targetEntity=MotCle::class)
     */
    private $motCles;

    /**
     * un article possède plusieurs commentaires.
     *
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="article", orphanRemoval=true)
     */
    private $commentaires;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->motCles = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(?string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getFeaturedImage(): ?string
    {
        return $this->featured_image;
    }

    public function setFeaturedImage(?string $featured_image): self
    {
        $this->featured_image = $featured_image;

        return $this;
    }

    public function getCreatedAt(): string
    {
        // on définit le format d'affichage de la date pour retourner une chaine de caractères directement
        return Carbon::parse($this->created_at)->locale('fr')->isoFormat('dddd Do MMMM YYYY à hh\hmm');
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): string
    {
        // on définit le format d'affichage de la date pour retourner une chaine de caractères directement
        return Carbon::parse($this->updated_at)->locale('fr')->isoFormat('dddd Do MMMM YYYY à hh\hmm');
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Categorie[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Categorie $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->addArticle($this);
        }

        return $this;
    }

    public function removeCategory(Categorie $category): self
    {
        if ($this->categories->removeElement($category)) {
            $category->removeArticle($this);
        }

        return $this;
    }

    /**
     * @return Collection|MotCle[]
     */
    public function getMotCles(): Collection
    {
        return $this->motCles;
    }

    public function addMotCle(MotCle $motCle): self
    {
        if (!$this->motCles->contains($motCle)) {
            $this->motCles[] = $motCle;
            $motCle->addArticle($this);
        }

        return $this;
    }

    public function removeMotCle(MotCle $motCle): self
    {
        if ($this->motCles->removeElement($motCle)) {
            $motCle->removeArticle($this);
        }

        return $this;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setArticle($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getArticle() === $this) {
                $commentaire->setArticle(null);
            }
        }

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use App\Entity\Categorie;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\MotCle;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titre')
            ->add('slug', null, [
                'required' => false,
            ])
            ->add('contenu')
            ->add('featured_image')
            ->add('categories', EntityType::class, [
                // looks for choices from this entity
                'class' => Categorie::class,

                // uses the User.username property as the visible option string
                'choice_label' => 'nom',

                // used to render a select box, check boxes or radios
                'multiple' => true,
                'expanded' => true,
            ])
            ->add('motCles', EntityType::class, [
                // looks for choices from this entity
                'class' => MotCle::class,

                // uses the User.username property as the visible option string
                'choice_label' => 'mot_cle',

                // used to render a select box, check boxes or radios
                'multiple' => true,
                'expanded' => true,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\CategorieRepository;
use App\Form\CommentaireType;
use App\Entity\Commentaire;

/**
 * @Route("/article")
 */
class ArticleController extends AbstractController
{
    /**
     * @Route("/", name="article_index", methods={"GET"})
     */
    public function index(): Response
    {
        // Cette méthode est réservée aux utilisateurs authentifiés
        $this->denyAccessUnlessGranted('ROLE_USER');

        return $this->render('article/index.html.twig', [
            'articles' => $this->getUser()->getArticles(),
        ]);
    }

    /**
     * @Route("/new", name="article_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        // Cette méthode est réservée aux utilisateurs authentifiés
        $this->denyAccessUnlessGranted('ROLE_USER');

        $article = new Article();

        // associer l'utilisateur courant au nouvel article
        $article->setUser($this->getUser());

        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // si le slug est vide, on le génère à partir du titre
            if (!$article->getSlug()) {
                $article->setSlug(strtolower(trim(preg_replace('/[^A-Za-z0-9-]+/', '-', $article->getTitre()))));
            }

            $article->setCreatedAt(new \DateTime());

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('article_index');
        }

        return $this->render('article/new.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="article_show", methods={"GET"})
     */
    public function show(Article $article): Response
    {
        $commentaire = new Commentaire();
        $form = $this->createForm(CommentaireType::class, $commentaire);

        return $this->render('article/show.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/edit", name="article_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Article $article, CategorieRepository $categorieRepository): Response
    {
        // Cette méthode est réservée aux utilisateurs authentifiés
        $this->denyAccessUnlessGranted('ROLE_USER');

        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $article->setUpdatedAt(new \DateTime());
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('article_index');
        }

        return $this->render('article/edit.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
            'categories' => $categorieRepository->findAll(),
        ]);
    }

    /**
     * @Route("/{id}", name="article_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Article $article): Response
    {
        // Cette méthode est réservée aux utilisateurs authentifiés
        $this->denyAccessUnlessGranted('ROLE_USER');

        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($article);
            $entityManager->flush();
        }

        return $this->redirectToRoute('article_index');
    }
}

templates/article/_categories.html.twig
<div>
{% for categorie in article.getCategories() %}
    <a href="{{ path('categorie_show', {'id': categorie.id}) }}"><span class="badge badge-warning">{{ categorie.nom }}</span></a>
{% endfor %}
</div>

templates/article/_comments.html.twig
<div class="row comments pt-4">
    <div class="col-sm-12">
        <h3>Commentaires à propos de l'article <span class="font-italic">{{ article.titre }}</span></h3>
        
        {% for commentaire in article.getCommentaires() %}
            <div class="card mt-4">
                <div class="card-header">{{ commentaire.pseudo }}, {{ commentaire.createdAt }}</div>
                <div class="card-body">
                    {{ commentaire.contenu }}
                </div>
            </div>
        {% endfor %}

        <div class="card border-primary mt-4">
            <div class="card-header">
            Nouveau commentaire
            </div>

            <div class="card-body">
                {{ form_start(form) }}
                    <div class="my-custom-class-for-errors">
                        {{ form_errors(form) }}
                    </div>

                    {{ form_row(form.pseudo) }}
                    
                    {{ form_row(form.contenu) }}
                    <input type="hidden" name="article_id" value="{{ article.id }}">
                    <button class="btn btn-primary float-right" type="submit">Poster le commentaire</button>
            </div>
        </div>
    </div>
</div>

templates/article/_delete_form.html.twig
<form method="post" class="d-inline" action="{{ path('article_delete', {'id': article.id}) }}" onsubmit="return confirm('Voulez-vous vraiment supprimer cet article ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn btn-danger btn-sm">Supprimer</button>
</form>

templates/article/_form.html.twig
{{ form_start(form) }}
    
    {{ form_row(form.titre) }}
    {{ form_row(form.slug, {'help': 'Si vous laissez vide, un slug sera généré automatiquement'}) }}
    {{ form_row(form.contenu) }}
    {{ form_row(form.featured_image, {'label': 'Image (doit être une URL accessible sur internet)'}) }}
    {{ form_row(form.categories) }}
    {{ form_row(form.motCles) }}

    <button class="d-inline btn btn-primary">{{ button_label|default('Publier') }}</button>
{{ form_end(form) }}

templates/article/_mots_cles.html.twig
<div>
{% for motCle in article.getMotCles %}
    <span class="text-secondary"><a href="{{ path('mot_cle_show', {'id': motCle.id}) }}">#{{ motCle.getMotCle }}</a></span>
{% endfor %}
</div>

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier l'article{% endblock %}

{% block body %}
    <h1>Modifier l'article</h1>

    {{ include('article/_form.html.twig', {'button_label': 'Mettre à jour'}) }}

    <a href="{{ path('article_index') }}">Retour à mes articles</a>
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes articles{% endblock %}

{% block body %}
    <h1>Mes articles</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Slug</th>
                <th>Date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for article in articles %}
            <tr>
                <td>{{ article.id }}</td>
                <td><a href="{{ path('article_show', {'id': article.id}) }}">{{ article.titre }}</a></td>
                <td>{{ article.slug }}</td>
                <td>{{ article.updatedAt ? article.updatedAt : (article.createdAt ?? 'inconnue') }}</td>
                <td>
                    <a href="{{ path('article_edit', {'id': article.id}) }}">Modifier</a>
                    {{ include('article/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">aucun article trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('article_new') }}">Nouvel article</a>
{% endblock %}

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvel article{% endblock %}

{% block body %}
    <h1>Nouvel article</h1>

    {{ include('article/_form.html.twig') }}

    <a href="{{ path('article_index') }}">Retour à la liste</a>
{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}The Nuum Blog - {{ article.titre }}{% endblock %}

{% block body %}

<div class="row post">
    <div class="col-sm-12">
        <div class="card">
            {% if article.featuredImage %}
                <img src="{{ article.getFeaturedImage }}" class="card-img-top post-image" alt="Image illustrative">
            {% else %}
                <img src="{{ "https://picsum.photos/seed/#{article.slug}/1200" }}" class="card-img-top post-image" alt="Une image au hasard">
            {% endif %}
            <div class="card-body">
                <h1 class="card-title">{{ article.titre }}</h1>
                {% include "article/_categories.html.twig" %}
                {% include "article/_mots_cles.html.twig" %}
                <p class="card-subtitle mb-2 mt-2 text-muted">Publié le {{ article.createdAt }}
                {# Si l'article a été mis à jour par la suite, l'afficher #}
                {% if article.updatedAt and article.createdAt != article.updatedAt %}
                (mis à jour le {{ article.updatedAt }})
                {% endif %}
                
                par <strong>{{ article.user.name }}</strong></p>

                <p class="card-text">{{ article.contenu | nl2br }}</p>
            </div>
        </div>
    </div>
</div>

<!-- Section des commentaires -->
{% include "article/_comments.html.twig" %}

<div class="row justify-content-center">
    <div class="column">
        <a href="{{ path('home') }}">Retour à l'accueil</a>
    </div>
</div>

{% endblock %}